version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: .
    ports:
      - "3050:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home/
      - /var/run/docker.sock:/var/run/docker.sock  

